#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose bases do not exceed four million
#find the sum of the even-based terms.

def sumEvenNumbers(maxNum):
	sum = 0
	currentNumber = 1
	previousNumber = 1
	while currentNumber <= maxNum:
		temp = currentNumber + previousNumber
		previousNumber = currentNumber
		currentNumber = temp
		if currentNumber % 2 == 0:
			sum+= currentNumber
	print sum

def main():
    sumEvenNumbers(4000000)


if __name__ == "__main__":
    main()